In [386]:
import pandas as pd
import csv
pd.set_option("display.max_rows", None, "display.max_columns", None)
import numpy as np
import time

In [391]:
Google_ads = pd.read_csv ('Google.csv')
Facebook_ads = pd.read_csv ('Facebook.csv')
Map = pd.read_csv ('map.csv')
Assignment_3 = pd.read_csv ('assignment_3.csv')
Google_ads['Date']= pd.to_datetime(Google_ads['Date'])
Facebook_ads['Date']= pd.to_datetime(Facebook_ads['Date'])
Assignment_3['Date']= pd.to_datetime(Assignment_3['Date'])

In [392]:
Facebook_ads['Conversions'] = Facebook_ads['Conversions 1D Click'] + Facebook_ads['Conversions 7D View']

In [393]:

Google_ads['Cost'] = Google_ads['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')
Facebook_ads['Cost'] = Facebook_ads['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')
Assignment_3['Cost'] = Assignment_3['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')

/var/folders/x_/94tnwtp142gf931j6d20vqk40000gq/T/ipykernel_89522/2443339641.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  Google_ads['Cost'] = Google_ads['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')
/var/folders/x_/94tnwtp142gf931j6d20vqk40000gq/T/ipykernel_89522/2443339641.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  Facebook_ads['Cost'] = Facebook_ads['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')
/var/folders/x_/94tnwtp142gf931j6d20vqk40000gq/T/ipykernel_89522/2443339641.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  Assignment_3['Cost'] = Assignment_3['Cost'].fillna(0.0).str.replace('[$,]', '').astype('float')

In [397]:
Assessment_1 = pd.concat([Google_ads, Facebook_ads]).groupby(['Date', 'Campaign']).sum().reset_index()
Assessment_1 = Assessment_1.drop(['Conversions 1D Click', 'Conversions 7D View'], axis = 1)

In [398]:
temp_df = Assessment_1.merge(Map, on='Campaign', how='inner').groupby(['Date', 'Campaign', 'Type', 'Impressions', 'Clicks', 'Conversions']).sum().reset_index()
temp_date_df = temp_df.loc[temp_df['Date'] < '1/6/22'].reset_index()
Assessment_2 = temp_date_df[(temp_date_df.Impressions > 1075 ) & (temp_date_df.Campaign == "Campaign_A") | (temp_date_df.Impressions < 875 ) & (temp_date_df.Campaign == "Campaign_B")  ]
Assessment_2 = Assessment_2.drop(['index','Clicks', 'Conversions','Cost'], axis = 1)

In [399]:
Assign_1 = Assessment_1[['Date', 'Campaign', 'Cost']]
Assign_1['Cost'] = Assign_1['Cost'].round(2)
diff_df = pd.merge(Assign_1, Assignment_3, how='outer', indicator='Exist')
diff_df = diff_df.loc[diff_df['Exist'] != 'both']
diff_df.drop(['Exist'], axis=1)

/var/folders/x_/94tnwtp142gf931j6d20vqk40000gq/T/ipykernel_89522/4057652706.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Assign_1['Cost'] = Assign_1['Cost'].round(2)

         Date    Campaign    Cost
0  2022-01-01  Campaign_A  199.65
7  2022-01-04  Campaign_B  278.96
11 2022-01-06  Campaign_B  273.41
16 2022-01-09  Campaign_A  319.34
20 2022-01-11  Campaign_A   19.89
21 2022-01-01  Campaign_A  199.85
22 2022-01-04  Campaign_B  279.24
23 2022-01-06  Campaign_A  273.41

         Date    Campaign    Cost
0  2022-01-01  Campaign_A  199.65
7  2022-01-04  Campaign_B  278.96
11 2022-01-06  Campaign_B  273.41
16 2022-01-09  Campaign_A  319.34
20 2022-01-11  Campaign_A   19.89
21 2022-01-01  Campaign_A  199.85
22 2022-01-04  Campaign_B  279.24
23 2022-01-06  Campaign_A  273.41

numpy.str_

In [284]:
df_diff = pd.concat([Assign_1,Assignment_3])

In [311]:
display(df_diff.dtypes)

Date        datetime64[ns]
Campaign            object
Cost               float64
dtype: object